# Generated by Django 5.2.17 on 2026-09-27 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='organization.empresa')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='organization.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='organization.empresa')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('tecnica', 'Tecnica'), ('blanda', 'Blanda'), ('idioma', 'Idioma'), ('otra', 'Otra')], max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilidades', to='organization.empresa')),
            ],
            options={
                'verbose_name': 'habilidad',
                'verbose_name_plural': 'habilidades',
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='CargoHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_requerido', models.PositiveSmallIntegerField(default=1)),
                ('obligatoria', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_requeridas', to='organization.cargo')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='organization.habilidad')),
            ],
            options={
                'verbose_name': 'habilidad del cargo',
                'verbose_name_plural': 'habilidades del cargo',
                'db_table': 'cargo_habilidad',
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('empresa', 'area', 'nombre'), name='cargo_unico_por_area'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='area_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='habilidad',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='habilidad_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='cargohabilidad',
            constraint=models.UniqueConstraint(fields=('cargo', 'habilidad'), name='habilidad_unica_por_cargo'),
        ),
    ]
