# Generated by Django 5.2.17 on 2026-09-27 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('PAS', 'Pasaporte'), ('PPT', 'Permiso por proteccion temporal')], max_length=20)),
                ('numero_documento', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('resumen', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='organization.empresa')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='HojaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='hojas_vida/')),
                ('texto_extraido', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_vida', to='people.persona')),
            ],
            options={
                'verbose_name': 'hoja de vida',
                'verbose_name_plural': 'hojas de vida',
                'db_table': 'hoja_vida',
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('tecnico', 'Tecnico'), ('pregrado', 'Pregrado'), ('posgrado', 'Posgrado'), ('curso', 'Curso')], max_length=40)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('en_curso', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='people.persona')),
            ],
            options={
                'verbose_name': 'formacion',
                'verbose_name_plural': 'formaciones',
                'db_table': 'formacion',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actualmente', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='people.persona')),
            ],
            options={
                'verbose_name': 'experiencia laboral',
                'verbose_name_plural': 'experiencias laborales',
                'db_table': 'experiencia_laboral',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('fijo', 'Fijo'), ('prestacion', 'Prestacion de servicios'), ('aprendizaje', 'Aprendizaje')], max_length=40)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organization.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organization.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organization.empresa')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empleado', to='people.persona')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='PersonaHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('extraida', 'Extraida'), ('validada', 'Validada')], default='manual', max_length=20)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='organization.habilidad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='people.persona')),
            ],
            options={
                'verbose_name': 'habilidad de la persona',
                'verbose_name_plural': 'habilidades de la persona',
                'db_table': 'persona_habilidad',
            },
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'numero_documento'), name='documento_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='personahabilidad',
            constraint=models.UniqueConstraint(fields=('persona', 'habilidad'), name='habilidad_unica_por_persona'),
        ),
    ]
