# Generated by Django 5.2.17 on 2026-09-27 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En revision'), ('entrevista', 'Entrevista'), ('prueba', 'Prueba'), ('seleccionada', 'Seleccionada'), ('descartada', 'Descartada'), ('contratada', 'Contratada')], default='recibida', max_length=20)),
                ('compatibilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('explicacion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to='people.persona')),
            ],
            options={
                'verbose_name': 'postulacion',
                'verbose_name_plural': 'postulaciones',
                'db_table': 'postulacion',
            },
        ),
        migrations.CreateModel(
            name='HistorialPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_de_postulacion', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='recruitment.postulacion')),
            ],
            options={
                'verbose_name': 'historial de postulacion',
                'verbose_name_plural': 'historial de postulaciones',
                'db_table': 'historial_postulacion',
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('continua', 'Continua'), ('no_continua', 'No continua')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('entrevistador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrevistas', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='recruitment.postulacion')),
            ],
            options={
                'verbose_name': 'entrevista',
                'verbose_name_plural': 'entrevistas',
                'db_table': 'entrevista',
            },
        ),
        migrations.CreateModel(
            name='AnalisisIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('extraccion', 'Extraccion'), ('compatibilidad', 'Compatibilidad'), ('preguntas', 'Preguntas')], max_length=40)),
                ('modelo', models.CharField(max_length=80)),
                ('resultado', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='recruitment.postulacion')),
            ],
            options={
                'verbose_name': 'analisis de IA',
                'verbose_name_plural': 'analisis de IA',
                'db_table': 'analisis_ia',
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Hibrido')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='organization.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='organization.cargo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='organization.empresa')),
            ],
            options={
                'verbose_name': 'vacante',
                'verbose_name_plural': 'vacantes',
                'db_table': 'vacante',
            },
        ),
        migrations.AddField(
            model_name='postulacion',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to='recruitment.vacante'),
        ),
        migrations.AddConstraint(
            model_name='postulacion',
            constraint=models.UniqueConstraint(fields=('vacante', 'persona'), name='postulacion_unica'),
        ),
    ]
