# Generated by Django 5.2.17 on 2026-09-27 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('tabla', models.CharField(max_length=80)),
                ('registro_id', models.BigIntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True)),
                ('direccion_ip', models.CharField(blank=True, max_length=45)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auditoria',
                'verbose_name_plural': 'auditorias',
                'db_table': 'auditoria',
            },
        ),
    ]
